---
- name: Add vlan to interface
  hosts: [rSeries]
  gather_facts: false
  connection: local

  vars:
    interface: "2.0"
    trunked_vlans: []

  tasks:

  - name: Login via uri (basic auth) Get token
    tags: auth
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-system:system/aaa'
      return_content: true
      force_basic_auth: true
      method: GET
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      headers:
        Content-Type: application/yang-data+json
      validate_certs: false
    register: token

  - name: Add vlan to interface 2
    tags: add_vlan
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-interfaces:interfaces/interface={{ interface }}/openconfig-if-ethernet:ethernet/openconfig-vlan:switched-vlan'
      return_content: true
      method: PUT
      body_format: json
      body: "{{ lookup('ansible.builtin.template', '../j2/vlan_interface.j2') }}"
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
      status_code: 204
    register: state_int_2
