---
- name: Create new tenant 
  hosts: [rSeries]
  gather_facts: no
  connection: local 

  vars_files:
    - create_tenant_vars.yaml

  tasks:

  - name: Login via uri (basic auth) Get token 
    tags: basic
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-system:system/aaa'
      return_content: true 
      force_basic_auth: true
      method: GET
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      headers:
        Content-Type: application/yang-data+json
      validate_certs: false
    register: token

  - name: Get System Health 
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-system:system/f5-system-health:health' 
      return_content: true
      method: GET
      body_format: json 
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
      status_code: 200
    register: health 

  - name: Show system health 
    ansible.builtin.debug:
      var: health

  - name: Health to file 
    ansible.builtin.copy:
      content: "{{ health | to_nice_json }}"
      dest: ../health/{{inventory_hostname}}_health.json 
    
