---
- name: lldp conf  
  hosts: [rSeries]
  gather_facts: no
  connection: local 

  tasks:

  - name: Login via uri (basic auth) Get token 
    tags: basic
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-system:system/aaa'
      return_content: true 
      force_basic_auth: true
      method: GET
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      headers:
        Content-Type: application/yang-data+json
      validate_certs: false
    register: token

  - name: Get lldp info 
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-lldp:lldp'
      return_content: true 
      method: GET
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
      status_code: 200
    register: lldp 

  - name: Show lldp 
    ansible.builtin.debug:
      var: lldp['json']['openconfig-lldp:lldp']

  - name: Get lldp neighbors
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-lldp:lldp/interfaces/interface=1.0/neighbors/neighbor'
      return_content: true 
      method: GET
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
      status_code: 200, 204
    register: lldp_neighbors 

  - name: show lldp neighbors 
    ansible.builtin.debug:
      var: lldp_neighbors['json']['openconfig-lldp:neighbor']

  - name: Get lldp neighbors
    ansible.builtin.uri:
      url: 'https://{{ ansible_host }}:{{ ansible_port }}/restconf/data/openconfig-lldp:lldp/interfaces/interface=2.0/config'
      return_content: true 
      method: PATCH
      body_format: json 
      body: "{{ lookup('ansible.builtin.template', '../j2/lldp.j2') }}"
      headers:
        Content-Type: application/yang-data+json
        X-Auth-Token: "{{ token.x_auth_token }}"
      validate_certs: false
      status_code: 200, 204
    register: lldp_int

  - name: show lldp neighbors 
    ansible.builtin.debug:
      var: lldp_int